# Generated by Django 5.1.1 on 2024-09-26 07:40

import event.models.services.event_cover_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(default=' ', upload_to=event.models.services.event_cover_path.event_cover_path, verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
