# Generated by Django 5.1.1 on 2024-10-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_cover_alter_event_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventshow',
            old_name='event_id',
            new_name='event',
        ),
    ]
