# Generated by Django 5.1.1 on 2024-10-07 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_event_id_eventshow_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Подробное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Длительность спектакля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='has_intermission',
            field=models.BooleanField(default=False, verbose_name='Есть антракт'),
        ),
        migrations.AddField(
            model_name='event',
            name='min_age_limit',
            field=models.IntegerField(default=0, help_text='Минимальный разрешенный возраст зрителя, например, 18 лет', verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='event',
            name='premiere_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата премьерыThe datetime and django.utils.timezone modules are available, so it is possible to provide e.g. timezone.now as a value.'),
            preserve_default=False,
        ),
    ]
