# Generated by Django 5.1.1 on 2024-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_description_event_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='premiere_at',
            field=models.DateField(verbose_name='Дата премьеры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=256, unique=True, verbose_name='Слаг названия'),
        ),
    ]
