# Generated by Django 5.1.1 on 2024-10-08 09:26

import django.db.models.deletion
import event.models.services.event_image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_premiere_at_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=event.models.services.event_image_path.event_image_path, verbose_name='Фото')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Фотография спектакля',
                'verbose_name_plural': 'Фотографии спектаклей',
            },
        ),
    ]
