# Generated by Django 5.1.1 on 2024-10-10 07:00

import django.utils.timezone
import event.models.services.event_cover_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventimage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preview_cover',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Обложка спектакля в афише на главной странице', upload_to=event.models.services.event_cover_path.event_cover_path, verbose_name='Обложка в афише'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(help_text='Горизонтальное изображение в карточке спектакля', upload_to=event.models.services.event_cover_path.event_cover_path, verbose_name='Обложка спектакля'),
        ),
    ]
