# Generated by Django 5.1.1 on 2024-10-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_preview_cover_alter_event_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventshow',
            name='link_to_buy_ticket',
            field=models.CharField(default='', max_length=256, verbose_name='Ссылка на покупку билетов'),
        ),
    ]
