# Generated by Django 5.1.1 on 2024-10-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_premiere_at_alter_event_slug'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpeople',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='event.event', verbose_name='Спектакль'),
        ),
    ]
