# Generated by Django 5.1.1 on 2024-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_eventpeople_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpeople',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
