# Generated by Django 5.1.1 on 2024-10-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_eventpeople_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpeople',
            name='role',
            field=models.CharField(default='', help_text='Если участник - актер: указать имя персонажа. Если участник выполняет другую роль, например, художник - нужно указать "художник"', max_length=256, verbose_name='Роль участника в спектакле'),
        ),
    ]
