# Generated by Django 5.1.1 on 2024-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_people_birthday_people_description_people_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.AddField(
            model_name='people',
            name='firstname',
            field=models.CharField(default='', max_length=512, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='lastname',
            field=models.CharField(default='', max_length=512, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
