# Generated by Django 5.1.1 on 2024-10-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_remove_people_name_people_firstname_people_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
