/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/event_show/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Show List Api */
        get: operations["event_api_get_event_show_list_api_get_event_show_list_api"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EventShowFilterSchema */
        EventShowFilterSchema: {
            /** Start At */
            start_at?: string | null;
        };
        /** EventSchema */
        EventSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Short Description */
            short_description: string;
            /** Cover */
            cover: string;
            /** Slug */
            slug: string;
        };
        /** EventShowSchema */
        EventShowSchema: {
            /** Id */
            id: number;
            event: components["schemas"]["EventSchema"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    event_api_get_event_show_list_api_get_event_show_list_api: {
        parameters: {
            query?: {
                start_at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventShowSchema"][];
                };
            };
        };
    };
}
